package suite

import "testing"

// T embeds *testing.T and provides convenient
// hooks for making assertions and other operations.
type T struct{ *testing.T }

type assertion func(actual interface{}, expected ...interface{}) error

// So is the signature assertion hook by which
// the caller provides the value generated by the
// system under test ('actual'), the (optional)
// value(s) against which to compare ('expected'),
// and the assertion function.
func (this *T) So(actual interface{}, assertion assertion, expected ...interface{}) {
	err := assertion(actual, expected...)
	if err != nil {
		this.Helper()
		this.Error(err)
	}
}

// Write implements io.Writer allowing for the
// suite to serve as a convenient log target,
// among other use cases.
func (this *T) Write(p []byte) (n int, err error) {
	this.Helper()
	this.Log(string(p))
	return len(p), nil
}
